config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "users/login", to: "sessions#new", as: "new_session"
  post "users/login", to: "sessions#create", as: "sessions"
  delete "users/logout", to: "sessions#destroy", as: "destroy_session"
  get "users/signup", to: "users#new"
  post "users/signup", to: "users#create"

  resources :articles

  root to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: :author_id

  validates :title, :content, presence: true
  has_rich_text :content

  def self.search(term)
    return all unless term

    Article.where("lower(title) LIKE :term", term: "%#{term.downcase}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password 

  has_many :articles, :foreign_key => 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy]
  before_action :check_logged_in, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @articles = Article.search(params[:q]).paginate(page: params[:page], per_page: 5)
  end

  def show
    @article = Article.find(params[:id])
    @article.increment!(:views_count)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.author_id = current_user.id
    if @article.save
      redirect_to articles_path
      flash[:notice] = "Article created!"
    else
      flash.now[:alert] = @article.errors.full_messages.join("\n")
      render "new"
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to articles_path
      flash[:notice] = "Article updated!"
    else
      render "edit"
      flash.now[:alert] = @article.errors.full_messages.join("\n")
    end
  end

  def destroy
    flash[:notice] = "Article deleted!" if @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = current_user.articles.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Only the owner of the article can do that."
    redirect_to articles_path
  end

  def article_params
    params.require(:article).permit(:title, :is_published, :publish_date, :content)
  end

  def check_logged_in
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "Logged out!"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome!"
      redirect_to root_path
    else
      flash.now[:alert] = @user.errors.full_messages.join("\n")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_key(key)
    if key == "notice"
      "success"
    else
      "danger"
    end
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<tr id="<%= dom_id(article) %>">
  <td class="title"><%= article.title %></td>
  <td class="views-count"><%= article.views_count %></td>
  <td class="author"><%= article.author.name %></td>
  <td class="publish-date"><%= article.publish_date %></td>
  <td class="links">
    <%= link_to "Edit", edit_article_path(article) %>
    <%= link_to "Show", article_path(article) %>
    <%= link_to "Delete", article_path(article), method: :delete %>
  </td>
</tr>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :is_published %>
    <%= f.check_box :is_published, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :publish_date %>
    <%= f.date_field :publish_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.rich_text_area :content, class: "form-control" %>
  </div>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/articles/edit.html.erb
<div class="container col-md-8">
  <h1>Edit Article</h1>

  <%= render "form" %>
</div>

app/views/articles/index.html.erb
<div class="container col-md-8">
  <h1><%= @articles.size %> Articles</h1>
  <div style="padding:10px; float:right"><%= link_to "New", new_article_path, class: "btn btn-primary" %></div>
  <div style="padding:10px; float:right">
    <%= form_tag articles_path, method: 'get' do %>
      <%= text_field_tag :q %>
      <%= submit_tag 'Search', class: "btn btn-success", style: "margin-left:10px"%>
    <% end %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Views Count</th>
        <th scope="col">Author</th>
        <th scope="col">Publish Date</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @articles %>
    </tbody>
  </table>
  <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/articles/new.html.erb
<div class="container col-md-8">
  <h1>New Article</h1>

  <%= render "form" %>
</div>

app/views/articles/show.html.erb
<div class="container col-md-8">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= @article.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= @article.publish_date %> by <%= @article.author.name %></h6>
      <p class="card-text"><%= @article.content %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <nav class="navbar navbar-light navbar-expand-sm">
      <%= link_to "Articles", root_path, class: "navbar-brand" %>
      <div class="container col-md-8">
        <ul class="navbar-nav ml-auto">
          <% if current_user %>
            <li class="nav-item">
              <%= link_to "Log out", destroy_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled"><%= current_user.email %></a>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign up", users_signup_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log in", new_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div id="flash_messages">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{flash_key(key)}") %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<div class="container col-md-8">
  <%= form_for @user, url: users_signup_path do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <%= f.submit "Sign Up", class: "btn btn-primary" %>
  <% end %>
</div>